### ISSUE TITLE
"% of people who used editor X" would be interesting not only for StreetComplete

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#16]
for StreetComplete there is the first graph on https://piebro.github.io/openstreetmap-statistics/#465b (BTW, is it feasible to have some human readable links? not this random anchors?)

**Comment by piebro** [comment]
I thought about it too and wanted it to look like this https://piebro.github.io/openstreetmap-statistics/#a008 , but I wasn't sure how to implement it, because adding up all percentages is more then 100% (people use more then one editing software) and I wasn't sure how to phrase it's not misleading. Maybe this can be a normal multi line plot.

It was like this before and I changed it to these random 4 digit hex numbers. The advantage is: smaller links, disadvantage: not human readable. Before it was #general__how_man_people_are_contributing_each_month (automatically generated from the topic and question). In the end I decided for the smaller links as a more elegant solution. It's pretty easy to change. Maybe something human generate tag that summarizes the data  is best of both worlds like #general_contributors_per_month for https://piebro.github.io/openstreetmap-statistics/#63f6

**Comment by matkoniecz** [comment]
> I thought about it too and wanted it to look like this https://piebro.github.io/openstreetmap-statistics/#a008 , but I wasn't sure how to implement it, because adding up all percentages is more then 100% (people use more then one editing software) 

Like on https://piebro.github.io/openstreetmap-statistics/#c229 ? With Y scale in %?

It would not sum to 100% obviously (in extreme theory all users could use all editors every single month) but that is not a problem.

**Comment by piebro** [comment]
Yes, I think that's the best way. I will add the plot.
