### ISSUE TITLE
show all quests, not just the most popular

### ISSUE THREAD

**Issue by matkoniecz** [piebro/OpenStreetMap-Statistics#2]
https://piebro.github.io/openstreetmap-statistics/#6773 is limited to 100 quests - why not show all of them? I am especially curious how unpopular are the least popular ones (AKA whatever it made sense to spend effort on implementing them)

**Comment by matkoniecz** [comment]
(it would be also cool to see more in https://piebro.github.io/openstreetmap-statistics/#d06d)

**Comment by piebro** [comment]
> https://piebro.github.io/openstreetmap-statistics/#6773 is limited to 100 quests - why not show all of them? I am especially curious how unpopular are the least popular ones (AKA whatever it made sense to spend effort on implementing them)

The number 100 is because I needed a threshold for editor software, imagery software and hashtags but there are not that many more quest so yes, good catch, it should show every quest.

> (it would be also cool to see more in https://piebro.github.io/openstreetmap-statistics/#d06d)

I tried it before with more quests but it gets messy with too many lines. Maybe 15 Quest is fine or there can be an other plot with all quests and people need to toggle some quests if they want to have an overview. What do you think?

**Comment by matkoniecz** [comment]
>  people need to toggle some quests if they want to have an overview. What do you think?

That would be cool! Or maybe dropdown menu to select quest to add them?

**Comment by piebro** [comment]
Yes, some kind of drop-down menu with multi selection might be more elegant. I think I will experiment with that.

**Comment by piebro** [comment]
I couldn't find a good UI element for a multi selection drop-down menu with about 150 elements. That's why I just added all traces to a new plot. To get a better overview one can click on a trace to enable or disable it. Double clicking a trace disables all other traces. I think there might be better solutions to this but I think this is alright and good for now. If you or anyone else have a better Idea of an UI element that's fitting feel free to open this issue again.

**Comment by matkoniecz** [comment]
@piebro Is it not deployed? Or is something now working fully?

(see https://piebro.github.io/openstreetmap-statistics/#6773 )

**Comment by piebro** [comment]
Everything is working, but changing the script isn't changing the data for the website directly. The script also need to be run. This can be done locally or with github [action](https://github.com/piebro/openstreetmap-statistics/blob/master/.github/workflows/main.yml) and takes about 2,5h. That's why I waited a little until there were a few changes.
I just merged the data update from github action. I messed up the merge a bit, but now everything should be fine and up-to-date (from 2h ago).

I saw just now that github is having issues deploying pages on their status page. Once it's resolved the website should also have the updates.

**Comment by matkoniecz** [comment]
> I saw just now that github is having issues deploying pages on their status page.

Oh, I was trying to debug on what is going on with https://github.com/matkoniecz/OSM-wikipedia-tag-validator-reports/actions/runs/3548712374 and another deployment that I was doing as part of paid work for someone else.

Thanks so much for that info.
