### ISSUE TITLE
The separation of digits of numbers broke the sorting of columns

### ISSUE THREAD

**Issue by deevroman** [piebro/OpenStreetMap-Statistics#91]
<img width="577" alt="Снимок экрана 2023-05-03 в 23 25 55" src="https://user-images.githubusercontent.com/25708359/236041745-381c4068-1dce-49e9-b034-4b8d2f5583d8.png">

**Comment by piebro** [comment]
Thanks, yes, that's an interesting bug. I use the JS function [toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) and I didn't realize that this has some other pretty wild number representations. I just switched to represent numbers with "," used in "en-US". All other text is in English anyway, so I think the localization does not make that much sense. This should be fixed with this patch #92.
